export const nigerianUniversities = [
  "Abia State University, Uturu",
  "Abia State Polytechnic",
  "Abia State College of Education",
  "Anambra State Polytechnic",
  "Adamawa State University, Mubi",
  "Adamawa State Polytechnic",
  "Adamawa State College of Education",
  "Adekunle Ajasin University, Akungba",
  "Akwa Ibom State University",
  "Akwa Ibom State Polytechnic",
  "Akwa Ibom State College of Education",
  "Ambrose Alli University, Ekpoma",
  "Achievers University, Owo",
  "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti",
  "African University Of Science And Technology, Abuja",
  "Abubakar Tafari Ali Polytechnic",
  "Akanu Ibiam Federal Polytechnic",
  "Auchi Polytechnic",
  "Abraham Adesanya Polytechnic",
  "Allover Central Polytechnic",
  "Abdul Gusau Polytechnic",
  "Ajayi Crowther University, Ibadan",
  "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Kastina",
  "American University Of Nigeria, Yola",
  "Augustine University",
  "Anchor University, Ayobo",
  "Arthur Javis University, Akpoyubo",
  "Admiralty University, Ibusa",
  "Atiba University, Oyo",
  "Ave Maria University, Piyanko",
  "Al-Istiqama University, Sumaila",
  "Ahman Pategi University",
  "Anan University, Kwall",
  "Al-Ansar University, Maiduguri",
  "Aletheia University, Ago-Iwoye",
  "Amadeus University, Amizi",
  "Azman University",
  "Amaj University, Kwali",
  "Al-Muhibbah Open University, Abuja",
  "Al-Bayan University, Ankpa",
  "Abubakar Tafawa Balewa University",
  "Ahmadu Bello University, Zaria",
  "Alex Ekwueme University, Ndufu-Alike",
  "Air Force Institute of Technology",
  "Adeyemi College of Education",
  "Alvan Ikoku College of Education",
  "Ansar-Ud-Deen College of Education",
  "African Thinkers Community of Inquiry College of Education",
  "Adamu Augie College of Education",
  "Adamu Tafawa Balewa College of Education",
  "Adeniran Ogunsanya College of Education",
  "Aminu Saleh College of Education",
  "Bauchi State University, Gadau",
  "Benue State University, Makurdi",
  "Benue State Polytechnic",
  "Borno State University, Maiduguri",
  "Bayelsa Medical University",
  "Bayelsa State College of Arts and Science",
  "Bamidele Olumilua University of Science and Technology, Ikere",
  "Babcock University",
  "Baze University",
  "Bells University of Technology, Otta",
  "Benson Idahosa University, Benin",
  "Bingham University, New Karu",
  "Bowen University, Iwo",
  "British Canadian University, Obufu",
  "Bayero University",
  "Bilyaminu Othman College of Education",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "Cross River State University of Technology",
  "Confluence University of Science and Technology, Osara",
  "Caleb University",
  "Caritas University",
  "Chrisland University",
  "Convenant University",
  "Crawford University",
  "Cresent University",
  "Christopher University",
  "Crown Hill University",
  "Coal City University",
  "Clifford University",
  "Claretian University of Nigeria",
  "Capital City University",
  "Canadian University of Nigeria, Abuja",
  "Cosmopolitan University Abuja",
  "College of Petroleum and Energy Studies",
  "Citi Polytechnic",
  "College of Agriculture and Animal Science",
  "College of Agriculture, Zuru",
  "College of Agriculture, Kabba",
  "Coastal Polytechnic",
  "College of Agriculture, Lafia",
  "College of Agriculture, Jalingo",
  "College of Education and Legal Studies, Nguru",
  "College of Education, Akamkpa",
  "College of Education, Akwanga",
  "College of Education, Billiri",
  "College of Education, Ekiadolor",
  "College of Education, Gindiri",
  "College of Education, Katsina-Ala",
  "College of Education, Lanlate",
  "College of Education, Oju",
  "College of Education, Waka-Biu",
  "College of Education, Warri",
  "Delta State University, Abraka",
  "Delta State Polytechnic",
  "Delta University of Science and Technology, Ozoro",
  "Dennis Osadebe University, Asaba",
  "Dominican University",
  "Dominion University",
  "Dorben Polytechnic",
  "Divine Polytechnic",
  "Ebonyi State University, Abakaliki",
  "Ebonyi State College of Education",
  "Ekiti State University",
  "Enugu State University of Science and Technology",
  "Enugu State Polytechnic",
  "Enugu State College of Education",
  "Edo State University",
  "Edo State Polytechnic",
  "Edo State College of Education",
  "Enugu State University of Medical and Applied Sciences, Igbo-Eno",
  "Emmanuel Alayande University of Education",
  "Edwin Clark University",
  "Elizade University",
  "Evangel University",
  "Eko University of Medical and Health Sciences Ijaniki",
  "Edusoko University, Bida",
  "European University of Nigeria, Duboyi",
  "Elrazi Medical University",
  "El-Amin University, Minna",
  "Eastern Polytechnic",
  "Ekwenugo Okeke Polytechnic",
  "Federal University of Health Sciences, Ila Orangun",
  "Federal University of Health Sciences, Azare",
  "Federal University of Technology, Ikot abasi",
  "Federal University of Technology, Babura",
  "Federal University of Agriculture, Zuru",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Health Technology, Otukpo",
  "Federal University, Gasau Zamfara",
  "Federal University, Birnin Kebbi",
  "Federal University, Wukari Taraba",
  "Federal University, Oye-Ekiti",
  "Federal University, Otuoke Bayelsa",
  "Federal University, Lokoja",
  "Federal University, Lafia",
  "Federal University, Kashere",
  "Federal University, Dutsin-Ma",
  "Federal University, Dutse",
  "Federal University of Technology, Owerri",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Akure",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University Gashua, Yobe",
  "Franco British International University",
  "Fountain University, Oshogbo",
  "Federal Polytechnic, Mubi",
  "Foundation College of Technology",
  "Federal Polytechnic, Oko",
  "Federal Polytechnic, Bauchi",
  "Federal Polytechnic, Ekowe Bayelsa",
  "Federal College of Agriculture, Ishiagu",
  "Federal Polytechnic, Ado-Ekiti",
  "Federal School of Dental Technology & Therapy",
  "Federal College of Land Resources Technology, Owerri",
  "Federal Polytechnic, Nekede",
  "Federal College of Forestry Mechanisation",
  "Federal School of Statistics, Manchok",
  "Federal Polytechnic, Bernin-Kebbi",
  "Federal Polytechnic, Idah",
  "Federal Polytechnic, Offa",
  "Federal College of Fisheries and Marine Technology",
  "Federal Polytechnic, Nasarawa",
  "Federal College of Fresh Water Fisheries Technology",
  "Federal College of Wildlife Management",
  "Federal Polytechnic, Bida",
  "Federal Polytechnic, Ilaro",
  "Federal Polytechnic, Ede",
  "Federal College of Animal Health & Production Technology",
  "Federal College of Forestry, Ibadan",
  "Federal Polytechnic, Ayede",
  "Federal College of Forestry, Jos",
  "Federal College of Land Resources Technology, Kuru",
  "Federal Polytechnic, Damaturu",
  "Federal Polytechnic, Namoda",
  "Federal College of Education, Oyo",
  "Federal College of Education, Iwo",
  "Federal College of Education, Asaba",
  "Federal College of Education, Abeokuta",
  "Federal College of Education, Kano",
  "Federal College of Education, Eha-Amufu",
  "Federal College of Education, Okene",
  "Federal College of Education, Gombe",
  "Federal College of Education, Omoku",
  "Federal College of Education, Kontagora",
  "Federal College of Education, Zaria",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Yola",
  "Federal College of Education, Potiskum",
  "Federal College of Education, Akoka",
  "Federal College of Education, Katsina",
  "Federal College of Education, Bichi",
  "Federal College of Education, Obudu",
  "Federal College of Education, Umunze",
  "FCT College of Education",
  "Gombe State University",
  "Gombe State University of Science and Technology",
  "Godfrey Okoye University",
  "Gregory University",
  "Greenfield University",
  "Gerar University of Medical Science",
  "Gateway Polytechnic",
  "Grace Polytechnic",
  "Hillside University of Science and Technology, Okemisi",
  "Hensard University, Toru-Orua",
  "Huda University, Gusau",
  "Havilla University, Nde-Ikom",
  "Hezekiah University",
  "Hallmark University",
  "Heritage Polytechnic",
  "Hussaini Adamu Federal Polytechnic",
  "Hassan Usman Kastina Polytechnic",
  "Havard Wilson College of Education",
  "Ibrahim Badamasi Babangida University",
  "Ignatius Ajuru University of Education",
  "Imo State University",
  "Igbinedion University Okada",
  "Iconic Open University",
  "Interlink Polytechnic",
  "Iwo City Polytechnic",
  "Igbajo Polytechnic",
  "Imo State Technological Skills Acquisition Center",
  "Imo State Polytechnic",
  "Institute of Management Technology",
  "Ibrahim Babangida College of Agriculture",
  "Imo State College of Education",
  "Isa Kaita College of Education",
  "Isaac Jasper Boro College of Education",
  "Institute of Ecumenical Education",
  "Joseph Ayo Babalola University",
  "Jewel University",
  "Jigawa State College of Education",
  "Jigawa State College of Education and Legal Studies",
  "King David Umahi University of Medical Sciences",
  "Khalifa Isiyaku Rabiu University",
  "Khadija University",
  "Karl-Kumm University",
  "Kola Daisi University",
  "Kwararafa University",
  "Kings University, Ode Omu",
  "Kingsley Ozumba Mbadiwe University",
  "Kwara State University",
  "Kebbi State University of Science and Technology",
  "Kano University of Science and Technology",
  "Kaduna State University",
  "Kwara State Polytechnic",
  "Kogi State Polytechnic",
  "Kebbi State Polytechnic",
  "Kano State Polytechnic",
  "Kaduna Polytechnic",
  "Kings Polytechnic",
  "Kano State College of Education and Preliminary Studies",
  "Kaduna State College of Education",
  "Kashim Ibrahim College of Education",
  "Kogi State College of Education",
  "Kwara State College of Education",
  "Ladoke Akintola University of Technology",
  "Lagos State University, Ojo",
  "Lagos State University of Education, ijanikin",
  "Lagos State University of Science and Technology, ikorodu",
  "Landmark University",
  "Lead City University",
  "Legacy University",
  "Lux Mundi University",
  "Lagos City Polytechnic",
  "Modibbo Adama University of Technology",
  "Michael Okpara University of Agriculture",
  "Miva Open University",
  "Mercy Medical University",
  "Maduka University",
  "Muhammad Kamalud University",
  "Margaret Lawrence University",
  "Mewar International University",
  "Maryam Abacha American University of Nigeria",
  "Mudiame University",
  "Maranathan University",
  "Mountain Top University",
  "Micheal & Cecilia Ibru University",
  "Mcpherson University",
  "Madonna University",
  "Moshood Abiola University of Science and Technology",
  "Mai Idris Alooma Polytechnic",
  "Moshood Abiola Polytechnic",
  "Maurid Institute of Management & Technology",
  "Mohammed Abdullahi Wase Polytechnic",
  "Maritime Academy of Nigeria",
  "Micheal Otedola College of Primary Education",
  "Mohammed Goni College of Legal and Islamic Studies",
  "Moje College of Education",
  "Muftau Olanihun College of Education",
  "Niger Delta University",
  "Nasarawa State University",
  "Nile University of Nigeria",
  "Novena University",
  "NOK University",
  "Nigerian British University",
  "Newgate University",
  "NorthWest University",
  "Nigerian University of Technology and Management",
  "National Open University of Nigeria",
  "Nigerian Police Academy, Wudil",
  "Nigerian Defence Academy",
  "Nnamdi Azikiwe University",
  "Nigerian Maritime University, Okerenkoko",
  "Nigerian Army University, Biu",
  "Nigerian Institute of Leather and Science Technology",
  "Nigerian College of Aviation Technology",
  "Nuhu Bamalli Polytechnic",
  "Nasarawa State Polytechnic",
  "Niger State College of Agriculture",
  "Niger State Polytechnic",
  "Novelty Polytechnic",
  "Nigerian Army School of Education",
  "Nana Aisahat Momorial College of Education",
  "Niger State College of Education",
  "Nwafor Orizu College of Education",
  "Obafemi Awolowo University",
  "Oduduwa University",
  "Obong University",
  "Ondo State University of Medical Sciences",
  "Oyo State Technical University",
  "Osun State University",
  "Olabisi Onabanjo University",
  "Ondo State University of Science and Technology",
  "Offer Center Institute of Agriculture",
  "Osun State Polytechnic",
  "Osun State College of Technology",
  "Ogun State College Of Health Technology",
  "Ogun State Institute Of Technology",
  "Our Saviour Institute Of Science and Technology",
  "Prince Abubakar Audu University",
  "Plateau State University",
  "Pan-Atlantic University",
  "Paul University",
  "Precious Cornerstone University",
  "PAMO University of Medical Sciences",
  "Philomath University",
  "PEN Resource University",
  "Peter University",
  "PeaceLand University",
  "Phoenix University",
  "Prime University",
  "Petroleum Training Institute",
  "Plateau State College of Agriculture",
  "Plateau State Polytechnic",
  "Port Harcourt Polytechnic",
  "Piaget College of Education",
  "Rivers State University",
  "Redeemer's University",
  "Renaissance University",
  "Rhema University",
  "Ritman University",
  "Rayhaan University",
  "Shanahan University",
  "Sam Maris University",
  "Saisa University of Medical Sciences and Technology",
  "Sports University",
  "Skyline University",
  "Spiritan University",
  "Summit University",
  "Southwestern University",
  "Samuel Adegboyega University",
  "Salem University",
  "Sa'adatu Rimi University",
  "Shehu Shagari University of Education",
  "Sokoto State University",
  "Sule Lamido University",
  "Tai Solarin University of Education",
  "Taraba State University",
  "Tansian University",
  "Trinity University",
  "TopFaith University",
  "Thomas Adewumi University",
  "The Duke Medical University",
  "Usumanu Danfodiyo University",
  "University of Uyo",
  "University of Port-Harcourt",
  "University of Nigeria, Nsukka",
  "University of Maiduguri",
  "University of Lagos",
  "University of Jos",
  "University of Ilorin",
  "University of Ibadan",
  "University of Calabar",
  "University of Benin",
  "University of Agriculture, Makurdi",
  "University of Abuja",
  "University of the Niger",
  "University of Offa",
  "University of Mkar",
  "University of Ilesa",
  "University of Delta",
  "University of Agriculture and Environmental Sciences",
  "University of Africa, Toru Orua",
  "Umar Musa Yar'Adua University",
  "Veritas University",
  "Vision University",
  "Venite University",
  "Wellspring University",
  "Wesley University",
  "Wigwe University",
  "Western Delta University",
  "West Midlands Open University",
  "Westland Delta University",
  "Yaba College Of Technology",
  "Yobe State University",
  "Yusuf Maitama Sule University",
  "Zamfara State University",
];
