export const serviceCategories = [
  "Assignment & Note Copying",
  "Car Rentals",
  "Cleaning & Household Services",
  "Computer & I.T Services",
  "Dj & Entertainment",
  "Fashion Designer",
  "Make-Up Artiste",
  "Hair Services",
  "Housing Agents",
  "Logistics & Delivery Services",
  "Party, Catering & Event Services",
  "Personal Shopper",
  "Photography & Video Services",
  "Printing",
  "Project Assistance",
];
